title: Default Page

tabs:
  # content tab
  content:
    label: Content
    icon: text
    fields:
      bodytext:
        label: Bodytext
        type: textarea
        counter: true
        size: medium

  # seo tab
  meta: tabs/meta
